test: fix system tests being flaky locally
The tests were failing with:
`TypeError: a.getClientExtensionResults is not a function`
I found out that we needed to add the function getClientExtensionResults
to the object that we are creating in the script.